RacingCompetition/RacingCompetition/Areas/Admin/Controllers/PlayerController.cs
using Autofac;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using RacingCompetition.Areas.Admin.Models;
using RacingCompetition.Models;
using System;

namespace RacingCompetition.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class PlayerController : Controller
    {
        private readonly ILogger<PlayerController> _logger;

        public PlayerController(ILogger<PlayerController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            _logger.LogInformation("\nFrom Index in Controller\n");
            //var model = new PlayerListModel();
            var model = Startup.AutofacContainer.Resolve<PlayerListModel>();
            return View(model);
        }

        public JsonResult GetPlayerData()
        {
            var dataTablesModel = new DataTablesAjaxRequestModel(Request);
            var model = new PlayerListModel();
            var data = model.GetPlayers(dataTablesModel);
            return Json(data);
        }

        public IActionResult Create()
        {
            var model = new CreatePlayerModel();
            return View(model);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult Create(CreatePlayerModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    throw new Exception();
                    model.CreatePlayer();
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", "Failed to create player");
                    _logger.LogError(ex, "Create Player Failed!");
                }
            }
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Edit(int id)
        {
            var model = new EditPlayerModel();
            model.LoadModelData(id);

            return View(model);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult Edit(EditPlayerModel model)
        {
            if (ModelState.IsValid)
            {
                model.Update();
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult Delete(int id)
        {
            var model = new PlayerListModel();
            model.Delete(id);

            return RedirectToAction(nameof(Index));
        }
    }
}

RacingCompetition/RacingCompetition/Areas/Admin/Views/Player/Create.cshtml
@model CreatePlayerModel
@{
    ViewData["Title"] = "Create";
}
<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Create A New Player</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Create Player</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card card-info">
                    <div class="card-header">
                        <h3 class="card-title">Add Player</h3>
                    </div>
                    <!-- /.card-header -->
                    <!-- form start -->
                    <form class="form-horizontal" method="post" asp-controller="Player"
                          asp-action="Create" asp-antiforgery="true">
                        <div asp-validation-summary="All" class="text-danger"></div>
                        <div class="card-body">
                            <div class="form-group row">
                                <label asp-for="Name" class="col-sm-2 col-form-label">Name</label>
                                <div class="col-sm-10">
                                    <input type="text" class="form-control" asp-for="Name"
                                           id="Name" placeholder="Player Name">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label asp-for="DateOfBirth" class="col-sm-2 col-form-label">Date Of Birth</label>
                                <div class="col-sm-10">
                                    <input type="date" asp-for="DateOfBirth" class="form-control"
                                           id="DateOfBirth" placeholder="DateOfBirth">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label asp-for="Address" class="col-sm-2 col-form-label">Address</label>
                                <div class="col-sm-10">
                                    <input type="text" class="form-control" asp-for="Address"
                                           id="Address" placeholder="Player Address">
                                </div>
                            </div>
                        </div>
                        <!-- /.card-body -->
                        <div class="card-footer">
                            <button type="submit" class="btn btn-info">Create</button>
                            <a asp-action="Index" asp-controller="Player"
                               class="btn btn-default float-right">Cancel</a>
                        </div>
                        <!-- /.card-footer -->
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

RacingCompetition/RacingCompetition/Areas/Admin/Views/Player/Edit.cshtml
@model EditPlayerModel
@{
    ViewData["Title"] = "Edit";
}
<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Edit An Existing Player</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Edit Player</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card card-info">
                    <div class="card-header">
                        <h3 class="card-title">Edit An Existing Player</h3>
                    </div>
                    <!-- /.card-header -->
                    <!-- form start -->
                    <form class="form-horizontal" method="post" asp-controller="Player"
                          asp-action="Edit" asp-antiforgery="true">
                        <div asp-validation-summary="All" class="text-danger"></div>
                        <input type="hidden" asp-for="Id" />
                        <div class="card-body">
                            <div class="form-group row">
                                <label asp-for="Name" class="col-sm-2 col-form-label">Name</label>
                                <div class="col-sm-10">
                                    <input type="text" class="form-control" asp-for="Name"
                                           id="Name" placeholder="Player Name">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label asp-for="DateOfBirth" class="col-sm-2 col-form-label">Date Of Birth</label>
                                <div class="col-sm-10">
                                    <input type="date" asp-for="DateOfBirth" class="form-control"
                                           id="DateOfBirth" placeholder="DateOfBirth">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label asp-for="Address" class="col-sm-2 col-form-label">Address</label>
                                <div class="col-sm-10">
                                    <input type="text" class="form-control" asp-for="Address"
                                           id="Address" placeholder="Player Address">
                                </div>
                            </div>
                        </div>
                        <!-- /.card-body -->
                        <div class="card-footer">
                            <button type="submit" class="btn btn-info">Edit</button>
                            <a asp-action="Index" asp-controller="Player"
                               class="btn btn-default float-right">Cancel</a>
                        </div>
                        <!-- /.card-footer -->
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

RacingCompetition/RacingCompetition/Areas/Admin/Views/Player/Index.cshtml
@model PlayerListModel
@{
    ViewData["Title"] = "Index";
}

@section Styles
{
    <link rel="stylesheet" href="/admin/plugins/datatables-bs4/css/dataTables.bootstrap4.css">
}

@section Scripts
{
    <script src="/admin/plugins/datatables/jquery.dataTables.js"></script>
    <script src="/admin/plugins/datatables-bs4/js/dataTables.bootstrap4.js"></script>
    <script>
        $(function () {
            $('#players').DataTable({
                "processing": true,
                "serverSide": true,
                "ajax": "/Admin/Player/GetPlayerData",

                "columnDefs": [
                    {
                        "orderable": false,
                        "targets": 4,
                        "render": function (data, type, row) {
                            return `<button type="submit" class="btn btn-info btn-sm" onclick="window.location.href='/admin/player/edit/${data}'" value='${data}'>
                                        <i class="fas fa-pencil-alt">
                                        </i>
                                        Edit
                                    </button>
                                    <button type="submit" class="btn btn-danger btn-sm show-bs-modal" href="#" data-id='${data}' value='${data}'>
                                        <i class="fas fa-trash">
                                        </i>
                                        Delete
                                    </button>`;
                        }
                    }
                ]

            });

            $('#players').on('click', '.show-bs-modal', function (event) {
                var id = $(this).data("id");
                var modal = $("#modal-default");
                modal.find('.modal-body p').text('Are you sure you want to delete this record?')
                $("#deleteId").val(id);
                $("#deleteForm").attr("action", "/admin/player/delete")
                modal.modal('show');
            });

            $("#deleteButton").click(function () {
                $("#deleteForm").submit();
            });
        });
    </script>
}

<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Available Players</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Players</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">All Available Players</h3>
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                    <table id="players" class="table table-bordered table-hover">
                        <thead>
                            <tr>
                                <th>Id</th>
                                <th>Name</th>
                                <th>Date Of Birth</th>
                                <th>Address</th>
                                <th style="width:200px">Action</th>
                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <th>Id</th>
                                <th>Name</th>
                                <th>Date Of Birth</th>
                                <th>Address</th>
                                <th>Action</th>
                            </tr>
                        </tfoot>
                    </table>
                    <partial name="_DeletePopupPartial" />
                </div>
                <!-- /.card-body -->
            </div>
            <!-- /.card -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>
<!-- /.content -->